# Generated by Django 2.2.4 on 2019-11-20 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.status'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugar',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.categoria'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugar',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.status'),
        ),
    ]
