# Generated by Django 2.2.4 on 2019-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0002_auto_20191120_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='urlFotos',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='urlMenu',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
