# Generated by Django 2.2.4 on 2019-12-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0004_remove_lugar_contadorfotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='placeid',
        ),
    ]
