# Generated by Django 2.2.4 on 2019-11-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
