# Generated by Django 2.2.4 on 2019-12-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0005_remove_lugar_placeid'),
        ('usuario', '0002_auto_20191125_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='lugar',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='lugar.lugar'),
            preserve_default=False,
        ),
    ]
